[package]
name = "ae3d-rust"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
gl = "0.14.0"
glm = "0.2.3"
json = "0.12.4"
obj = "0.10.2"
stb_image = "0.3.0"

[dependencies.sdl2]
version = "0.37.0"
features = ["image", "ttf"]
